


# Permalinks
permalink:        pretty

# Setup
title:            MID project validator
tagline:          'Valid contents of projects following MID conventions'
description:      'A cross-platform library for validating structure and contents of digital editing projects'


baseurl: '/projectvalidator/'


author:
  name:           'Neel Smith'


links:
  - title:  Github repository
    url:  https://github.com/HCMID/projectvalidator
    external: true
